require 'yaml'

def ip_config(config, provider)
  if ENV["BOX_STATIC_IP"] == "1"

    if provider == "virtualbox"
      ip = "192.168.201.176"
      ip6 = "fde4:8dba:82e1::c4"
    elsif provider == "libvirt"
      ip = "192.168.151.101"
      ip6 = "fde4:8dba:82e1::c5"
    else
      raise Vagrant::Errors::VagrantError.new, "Unknown provider: %s" % provider
    end

    ip = ENV["BOX_USE_IPV6"] == "1" ? ip6 : ip

    config.vm.network "private_network", ip: ip

    config.vm.provision "check_ip", type: "shell" do |shell|
      shell.path = "check_ip.sh"
      shell.env = { "BOX_IP" => ip }
    end
  end
end

Vagrant.configure("2") do |config|

  config.vm.hostname = "vm-test"

  jenkins_jobs = YAML::load_file('../vagrant-build-images.yaml')

  jenkins_jobs.each do |item|
    if item.key?("project")
      if item["project"]["provider"] == "libvirt"
        config.vm.define item["project"]["distro"] do |distro|
          distro.vm.box = item["project"]["boxname"]
          distro.vm.box_url = item["project"]["trigger_url"]
        end
      end
    end
  end

  config.vm.provision "shell", path: "prepare_repos.sh"

  config.vm.provider "virtualbox" do |virtbox, override|
    virtbox.memory = 2048
    virtbox.cpus = 4
    ip_config(override, "virtualbox")
  end

  config.vm.provider :libvirt do |libvirt, override|
    libvirt.cpus = 4
    libvirt.memory = 2048
    ip_config(override, "libvirt")
  end

  if ENV["BOX_STATIC_IP"] != "1"
    config.vm.provision :ansible do |ansible|
      ansible.playbook = "ansible_playbook.yml"
      ansible.become = true
      ansible.become_user = "root"
      ansible.verbose = "-vv"
    end
  end


  # TODO: add a salt state

end
